server:
  port: 8090

cloud:
 # db-host: localhost
  eureka-host: localhost
  kafka-host: localhost
  currency-url: http://localhost:8080
  auth-token-url: http://localhost:9001/validate
  user-info-url: http://localhost:9001/user

spring:
  application:
    name: exchange-processing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/account
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 221255aa
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    producer:
      bootstrap-servers: ${cloud.kafka-host}:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  currency:
    url: ${cloud.currency-url}

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
